[phases.setup]
nixPkgs = ["python311", "unzip", "nodejs_20"]

[phases.install]
cmds = ["python -m venv .venv", ". .venv/bin/activate && pip install -r requirements.txt"]

[phases.build]
cmds = [". .venv/bin/activate && reflex init"]

[start]
cmd = ". .venv/bin/activate && reflex run --env prod"
