[phases.setup]
nixPkgs = ["python311", "unzip", "nodejs_20"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r requirements.txt"]

[phases.build]
cmds = ["python -m reflex init"]

[start]
cmd = "python -m reflex run --env prod --backend-only & python -m reflex run --env prod --frontend-only"
